In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import seaborn as sns
from sklearn.model_selection import train_test_split

In [2]:
df_rta = pd.read_csv("RTA Dataset.csv")

In [3]:
df_rta

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,Employee,1-2yr,Automobile,Owner,Above 10yr,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Moving Backward,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Employee,Above 10yr,Public (> 45 seats),Owner,5-10yrs,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,Employee,1-2yr,Lorry (41?100Q),Owner,NaN,...,Going straight,Driver or rider,Male,31-50,3,Driver,NaN,Not a Pedestrian,Changing lane to the left,Serious Injury
3,1:06:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Public (> 45 seats),Governmental,NaN,...,Going straight,Pedestrian,Female,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
4,1:06:00,Sunday,18-30,Male,Junior high school,Employee,2-5yr,NaN,Owner,5-10yrs,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12311,16:15:00,Wednesday,31-50,Male,NaN,Employee,2-5yr,Lorry (11?40Q),Owner,NaN,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury
12312,18:00:00,Sunday,Unknown,Male,Elementary school,Employee,5-10yr,Automobile,Owner,NaN,...,Other,na,na,na,na,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury
12313,13:55:00,Sunday,Over 51,Male,Junior high school,Employee,5-10yr,Bajaj,Owner,2-5yrs,...,Other,Driver or rider,Male,31-50,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Serious Injury
12314,13:55:00,Sunday,18-30,Female,Junior high school,Employee,Above 10yr,Lorry (41?100Q),Owner,2-5yrs,...,Other,na,na,na,na,Driver,Normal,Not a Pedestrian,Driving under the influence of drugs,Slight Injury
12315,13:55:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Other,Owner,2-5yrs,...,Stopping,Pedestrian,Female,5,3,Driver,Normal,Crossing from nearside - masked by parked or s...,Changing lane to the right,Slight Injury

In [4]:
df_rta.head()

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,Employee,1-2yr,Automobile,Owner,Above 10yr,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Moving Backward,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Employee,Above 10yr,Public (> 45 seats),Owner,5-10yrs,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,Employee,1-2yr,Lorry (41?100Q),Owner,NaN,...,Going straight,Driver or rider,Male,31-50,3,Driver,NaN,Not a Pedestrian,Changing lane to the left,Serious Injury
3,1:06:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Public (> 45 seats),Governmental,NaN,...,Going straight,Pedestrian,Female,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
4,1:06:00,Sunday,18-30,Male,Junior high school,Employee,2-5yr,NaN,Owner,5-10yrs,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury

In [5]:
df_rta.describe()

       Number_of_vehicles_involved  Number_of_casualties
count                 12316.000000          12316.000000
mean                      2.040679              1.548149
std                       0.688790              1.007179
min                       1.000000              1.000000
25%                       2.000000              1.000000
50%                       2.000000              1.000000
75%                       2.000000              2.000000
max                       7.000000              8.000000

In [6]:
bad_columns = ["Casualty_class", "Casualty_severity", "Work_of_casuality", "Fitness_of_casuality", "Vehicle_driver_relation"]

df_remove_col = df_rta.drop(columns=bad_columns)

In [7]:
df_remove_col.head()

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,Defect_of_vehicle,...,Weather_conditions,Type_of_collision,Number_of_vehicles_involved,Number_of_casualties,Vehicle_movement,Sex_of_casualty,Age_band_of_casualty,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,1-2yr,Automobile,Owner,Above 10yr,No defect,...,Normal,Collision with roadside-parked vehicles,2,2,Going straight,na,na,Not a Pedestrian,Moving Backward,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Above 10yr,Public (> 45 seats),Owner,5-10yrs,No defect,...,Normal,Vehicle with vehicle collision,2,2,Going straight,na,na,Not a Pedestrian,Overtaking,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,1-2yr,Lorry (41?100Q),Owner,NaN,No defect,...,Normal,Collision with roadside objects,2,2,Going straight,Male,31-50,Not a Pedestrian,Changing lane to the left,Serious Injury
3,1:06:00,Sunday,18-30,Male,Junior high school,5-10yr,Public (> 45 seats),Governmental,NaN,No defect,...,Normal,Vehicle with vehicle collision,2,2,Going straight,Female,18-30,Not a Pedestrian,Changing lane to the right,Slight Injury
4,1:06:00,Sunday,18-30,Male,Junior high school,2-5yr,NaN,Owner,5-10yrs,No defect,...,Normal,Vehicle with vehicle collision,2,2,Going straight,na,na,Not a Pedestrian,Overtaking,Slight Injury

In [8]:
df_remove_col.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12316 entries, 0 to 12315
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Time                         12316 non-null  object
 1   Day_of_week                  12316 non-null  object
 2   Age_band_of_driver           12316 non-null  object
 3   Sex_of_driver                12316 non-null  object
 4   Educational_level            11575 non-null  object
 5   Driving_experience           11487 non-null  object
 6   Type_of_vehicle              11366 non-null  object
 7   Owner_of_vehicle             11834 non-null  object
 8   Service_year_of_vehicle      8388 non-null   object
 9   Defect_of_vehicle            7889 non-null   object
 10  Area_accident_occured        12077 non-null  object
 11  Lanes_or_Medians             11931 non-null  object
 12  Road_allignment              12174 non-null  object
 13  Types_of_Junction            11429 non-null  object
 14  Road_surface_type            12144 non-null  object
 15  Road_surface_conditions      12316 non-null  object
 16  Light_conditions             12316 non-null  object
 17  Weather_conditions           12316 non-null  object
 18  Type_of_collision            12161 non-null  object
 19  Number_of_vehicles_involved  12316 non-null  int64
 20  Number_of_casualties         12316 non-null  int64
 21  Vehicle_movement             12008 non-null  object
 22  Sex_of_casualty              12316 non-null  object
 23  Age_band_of_casualty         12316 non-null  object
 24  Pedestrian_movement          12316 non-null  object
 25  Cause_of_accident            12316 non-null  object
 26  Accident_severity            12316 non-null  object
dtypes: int64(2), object(25)
memory usage: 2.5+ MB

In [9]:
## Normalize the Driving experience column

df_rta_normalize = df_remove_col.replace({"Driving_experience" : {'unknown' : 'Unknown'}})
df_rta_no_null = df_rta_normalize.fillna("Unknown")

df_rta_no_null = df_rta_no_null.replace("Unknown", method="ffill")
df_rta_Values = df_rta_no_null.replace("Unknown", method="bfill")

In [10]:
df_rta_Values.head(20)

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,Defect_of_vehicle,...,Weather_conditions,Type_of_collision,Number_of_vehicles_involved,Number_of_casualties,Vehicle_movement,Sex_of_casualty,Age_band_of_casualty,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,1-2yr,Automobile,Owner,Above 10yr,No defect,...,Normal,Collision with roadside-parked vehicles,2,2,Going straight,na,na,Not a Pedestrian,Moving Backward,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Above 10yr,Public (> 45 seats),Owner,5-10yrs,No defect,...,Normal,Vehicle with vehicle collision,2,2,Going straight,na,na,Not a Pedestrian,Overtaking,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,1-2yr,Lorry (41?100Q),Owner,5-10yrs,No defect,...,Normal,Collision with roadside objects,2,2,Going straight,Male,31-50,Not a Pedestrian,Changing lane to the left,Serious Injury
3,1:06:00,Sunday,18-30,Male,Junior high school,5-10yr,Public (> 45 seats),Governmental,5-10yrs,No defect,...,Normal,Vehicle with vehicle collision,2,2,Going straight,Female,18-30,Not a Pedestrian,Changing lane to the right,Slight Injury
4,1:06:00,Sunday,18-30,Male,Junior high school,2-5yr,Public (> 45 seats),Owner,5-10yrs,No defect,...,Normal,Vehicle with vehicle collision,2,2,Going straight,na,na,Not a Pedestrian,Overtaking,Slight Injury
5,14:15:00,Friday,31-50,Male,Junior high school,2-5yr,Public (> 45 seats),Owner,5-10yrs,No defect,...,Normal,Vehicle with vehicle collision,1,1,U-Turn,Male,31-50,Not a Pedestrian,Overloading,Slight Injury
6,17:30:00,Wednesday,18-30,Male,Junior high school,2-5yr,Automobile,Owner,5-10yrs,No defect,...,Normal,Vehicle with vehicle collision,1,1,Moving Backward,Female,18-30,Not a Pedestrian,Other,Slight Injury
7,17:20:00,Friday,18-30,Male,Junior high school,2-5yr,Automobile,Governmental,Above 10yr,No defect,...,Normal,Vehicle with vehicle collision,2,1,U-Turn,na,na,Not a Pedestrian,No priority to vehicle,Slight Injury
8,17:20:00,Friday,18-30,Male,Junior high school,Above 10yr,Lorry (41?100Q),Owner,1-2yr,No defect,...,Normal,Collision with roadside-parked vehicles,2,1,Going straight,Male,Under 18,Crossing from driver's nearside,Changing lane to the right,Slight Injury
9,17:20:00,Friday,18-30,Male,Junior high school,1-2yr,Automobile,Owner,2-5yrs,No defect,...,Normal,Collision with roadside-parked vehicles,2,1,U-Turn,Male,18-30,Not a Pedestrian,Moving Backward,Serious Injury
10,14:40:00,Saturday,18-30,Male,Above high school,1-2yr,Public (13?45 seats),Owner,2-5yrs,No defect,...,Normal,Collision with animals,2,1,Turnover,na,na,Not a Pedestrian,Changing lane to the left,Serious Injury
11,14:40:00,Saturday,31-50,Male,Above high school,No Licence,Automobile,Owner,2-5yrs,No defect,...,Normal,Collision with animals,2,1,Going straight,Male,18-30,Not a Pedestrian,No priority to pedestrian,Serious Injury
12,17:45:00,Thursday,18-30,Male,Junior high school,1-2yr,Public (> 45 seats),Owner,2-5yrs,No defect,...,Normal,Collision with animals,2,2,Going straight,na,na,Not a Pedestrian,No distancing,Slight Injury
13,17:45:00,Thursday,31-50,Male,Junior high school,5-10yr,Lorry (41?100Q),Owner,Above 10yr,No defect,...,Normal,Collision with animals,2,2,Waiting to go,na,na,Not a Pedestrian,No priority to vehicle,Slight Injury
14,17:45:00,Thursday,31-50,Male,Junior high school,Above 10yr,Automobile,Owner,1-2yr,No defect,...,Normal,Collision with animals,2,2,Going straight,Female,18-30,Not a Pedestrian,No distancing,Serious Injury
15,22:45:00,Monday,18-30,Female,Junior high school,Above 10yr,Lorry (11?40Q),Owner,1-2yr,No defect,...,Raining,Collision with animals,2,3,Going straight,na,na,Not a Pedestrian,No distancing,Serious Injury
16,22:45:00,Monday,18-30,Male,Junior high school,5-10yr,Public (13?45 seats),Owner,1-2yr,No defect,...,Raining,Collision with animals,2,3,Going straight,na,na,Not a Pedestrian,Moving Backward,Slight Injury
17,22:45:00,Monday,18-30,Male,Elementary school,2-5yr,Public (13?45 seats),Owner,1-2yr,No defect,...,Raining,Collision with animals,2,3,Going straight,na,na,Not a Pedestrian,Changing lane to the right,Serious Injury
18,22:45:00,Monday,18-30,Male,Junior high school,2-5yr,Public (13?45 seats),Owner,Above 10yr,No defect,...,Raining,Collision with animals,2,3,Moving Backward,na,na,Not a Pedestrian,No priority to pedestrian,Slight Injury
19,8:20:00,Tuesday,18-30,Male,Junior high school,Below 1yr,Long lorry,Owner,5-10yrs,No defect,...,Normal,Collision with animals,2,1,Going straight,Male,Under 18,Not a Pedestrian,Moving Backward,Serious Injury

In [11]:
df_rta_Values.isnull().sum()

Time                           0
Day_of_week                    0
Age_band_of_driver             0
Sex_of_driver                  0
Educational_level              0
Driving_experience             0
Type_of_vehicle                0
Owner_of_vehicle               0
Service_year_of_vehicle        0
Defect_of_vehicle              0
Area_accident_occured          0
Lanes_or_Medians               0
Road_allignment                0
Types_of_Junction              0
Road_surface_type              0
Road_surface_conditions        0
Light_conditions               0
Weather_conditions             0
Type_of_collision              0
Number_of_vehicles_involved    0
Number_of_casualties           0
Vehicle_movement               0
Sex_of_casualty                0
Age_band_of_casualty           0
Pedestrian_movement            0
Cause_of_accident              0
Accident_severity              0
dtype: int64

In [12]:
df_rta_Values.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12316 entries, 0 to 12315
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Time                         12316 non-null  object
 1   Day_of_week                  12316 non-null  object
 2   Age_band_of_driver           12316 non-null  object
 3   Sex_of_driver                12316 non-null  object
 4   Educational_level            12316 non-null  object
 5   Driving_experience           12316 non-null  object
 6   Type_of_vehicle              12316 non-null  object
 7   Owner_of_vehicle             12316 non-null  object
 8   Service_year_of_vehicle      12316 non-null  object
 9   Defect_of_vehicle            12316 non-null  object
 10  Area_accident_occured        12316 non-null  object
 11  Lanes_or_Medians             12316 non-null  object
 12  Road_allignment              12316 non-null  object
 13  Types_of_Junction            12316 non-null  object
 14  Road_surface_type            12316 non-null  object
 15  Road_surface_conditions      12316 non-null  object
 16  Light_conditions             12316 non-null  object
 17  Weather_conditions           12316 non-null  object
 18  Type_of_collision            12316 non-null  object
 19  Number_of_vehicles_involved  12316 non-null  int64
 20  Number_of_casualties         12316 non-null  int64
 21  Vehicle_movement             12316 non-null  object
 22  Sex_of_casualty              12316 non-null  object
 23  Age_band_of_casualty         12316 non-null  object
 24  Pedestrian_movement          12316 non-null  object
 25  Cause_of_accident            12316 non-null  object
 26  Accident_severity            12316 non-null  object
dtypes: int64(2), object(25)
memory usage: 2.5+ MB

In [13]:
##Converting the Time column to Night/Day from HH:MM:SS

def convert_time(t):
    
    t = t[:2]
    
    if ":" in t:
        t = t[:1]
    return int(t)

def Cat_Time_col(t):
    
    if t >=6 and t < 18:
        return "Day"
    
    else:
        return "Night"
    
df_rta_Values["Time"] = df_rta_Values["Time"].apply(lambda x : convert_time(x))
df_rta_Values["Time"] = df_rta_Values["Time"].apply(lambda x : Cat_Time_col(x))

In [14]:
df_rta_Values["Time"].value_counts(dropna=False)

Day      8361
Night    3955
Name: Time, dtype: int64

In [15]:
## Converting each of the columns from categorical to numericals

df_rta_mapping = df_rta_Values

df_rta_Values["Sex_of_driver"] = df_rta_Values["Sex_of_driver"].map({"Male" : 1, "Female" : 0})
df_rta_Values["Time"] = df_rta_Values["Time"].map({"Day" : 1, "Night": 0})
df_rta_Values["Driving_experience"] = df_rta_Values["Driving_experience"].map({'No Licence': 0, 'Below 1yr': 1, '1-2yr': 2, '2-5yr': 3, '5-10yr': 4, 'Above 10yr': 5})
df_rta_Values["Educational_level"] = df_rta_Values["Educational_level"].map({'Illiterate': 0, 'Writing & reading': 1, 'Elementary school': 2, 'Junior high school': 3, 'High school': 4, 'Above high school': 5})
df_rta_Values["Accident_severity"] = df_rta_Values["Accident_severity"].map({'Slight Injury': 0, 'Serious Injury': 1, 'Fatal injury': 2})
df_rta_Values["Age_band_of_driver"] = df_rta_Values["Age_band_of_driver"].map({'Under 18': 0, '18-30': 1, '31-50': 2, 'Over 51': 3})
 
df_rta_afterMap = df_rta_Values

In [16]:
df_rta_afterMap.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12316 entries, 0 to 12315
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Time                         12316 non-null  int64
 1   Day_of_week                  12316 non-null  object
 2   Age_band_of_driver           12316 non-null  int64
 3   Sex_of_driver                12316 non-null  int64
 4   Educational_level            12316 non-null  int64
 5   Driving_experience           12316 non-null  int64
 6   Type_of_vehicle              12316 non-null  object
 7   Owner_of_vehicle             12316 non-null  object
 8   Service_year_of_vehicle      12316 non-null  object
 9   Defect_of_vehicle            12316 non-null  object
 10  Area_accident_occured        12316 non-null  object
 11  Lanes_or_Medians             12316 non-null  object
 12  Road_allignment              12316 non-null  object
 13  Types_of_Junction            12316 non-null  object
 14  Road_surface_type            12316 non-null  object
 15  Road_surface_conditions      12316 non-null  object
 16  Light_conditions             12316 non-null  object
 17  Weather_conditions           12316 non-null  object
 18  Type_of_collision            12316 non-null  object
 19  Number_of_vehicles_involved  12316 non-null  int64
 20  Number_of_casualties         12316 non-null  int64
 21  Vehicle_movement             12316 non-null  object
 22  Sex_of_casualty              12316 non-null  object
 23  Age_band_of_casualty         12316 non-null  object
 24  Pedestrian_movement          12316 non-null  object
 25  Cause_of_accident            12316 non-null  object
 26  Accident_severity            12316 non-null  int64
dtypes: int64(8), object(19)
memory usage: 2.5+ MB

In [17]:
## Now next step would be to convert the remaining set of columns to the numericals

col_mapped = ['Driving_experience', 'Sex_of_driver', 'Age_band_of_driver', 'Educational_level', 'Time', 'Accident_severity']

In [18]:
columns = list(df_rta_afterMap.columns)
int_columns = ["Number_of_vehicles_involved", "Number_of_casualties"]
total_int_columns = int_columns + col_mapped

remaining_col_covertion = list(set(columns) - set(total_int_columns))
print("Resultant Columns :", remaining_col_covertion)

Resultant Columns : ['Owner_of_vehicle', 'Age_band_of_casualty', 'Day_of_week', 'Sex_of_casualty', 'Type_of_vehicle', 'Road_allignment', 'Area_accident_occured', 'Weather_conditions', 'Type_of_collision', 'Types_of_Junction', 'Road_surface_conditions', 'Lanes_or_Medians', 'Pedestrian_movement', 'Cause_of_accident', 'Service_year_of_vehicle', 'Road_surface_type', 'Vehicle_movement', 'Defect_of_vehicle', 'Light_conditions']

In [19]:
## Use get_dummies to convert into the numerical values

df_rta_dummies = pd.get_dummies(df_rta_afterMap, columns= remaining_col_covertion)

df_rta_dummies

,Time,Age_band_of_driver,Sex_of_driver,Educational_level,Driving_experience,Number_of_vehicles_involved,Number_of_casualties,Accident_severity,Owner_of_vehicle_Governmental,Owner_of_vehicle_Organization,...,Vehicle_movement_Turnover,Vehicle_movement_U-Turn,Vehicle_movement_Waiting to go,Defect_of_vehicle_5,Defect_of_vehicle_7,Defect_of_vehicle_No defect,Light_conditions_Darkness - lights lit,Light_conditions_Darkness - lights unlit,Light_conditions_Darkness - no lighting,Light_conditions_Daylight
0,1,1,1,5,2,2,2,0,0,0,...,0,0,0,0,0,1,0,0,0,1
1,1,2,1,3,5,2,2,0,0,0,...,0,0,0,0,0,1,0,0,0,1
2,1,1,1,3,2,2,2,1,0,0,...,0,0,0,0,0,1,0,0,0,1
3,0,1,1,3,4,2,2,0,1,0,...,0,0,0,0,0,1,1,0,0,0
4,0,1,1,3,3,2,2,0,0,0,...,0,0,0,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12311,1,2,1,2,3,2,1,0,0,0,...,0,0,0,0,0,1,0,0,0,1
12312,0,2,1,2,4,2,1,0,0,0,...,0,0,0,0,0,1,0,0,0,1
12313,1,3,1,3,4,1,1,1,0,0,...,0,0,0,0,0,1,0,0,0,1
12314,1,1,0,3,5,2,1,0,0,0,...,0,0,0,0,0,1,1,0,0,0
12315,1,1,1,3,4,2,1,0,0,0,...,0,0,0,0,0,1,1,0,0,0

In [20]:
df_rta_dummies.head(20)

,Time,Age_band_of_driver,Sex_of_driver,Educational_level,Driving_experience,Number_of_vehicles_involved,Number_of_casualties,Accident_severity,Owner_of_vehicle_Governmental,Owner_of_vehicle_Organization,...,Vehicle_movement_Turnover,Vehicle_movement_U-Turn,Vehicle_movement_Waiting to go,Defect_of_vehicle_5,Defect_of_vehicle_7,Defect_of_vehicle_No defect,Light_conditions_Darkness - lights lit,Light_conditions_Darkness - lights unlit,Light_conditions_Darkness - no lighting,Light_conditions_Daylight
0,1,1,1,5,2,2,2,0,0,0,...,0,0,0,0,0,1,0,0,0,1
1,1,2,1,3,5,2,2,0,0,0,...,0,0,0,0,0,1,0,0,0,1
2,1,1,1,3,2,2,2,1,0,0,...,0,0,0,0,0,1,0,0,0,1
3,0,1,1,3,4,2,2,0,1,0,...,0,0,0,0,0,1,1,0,0,0
4,0,1,1,3,3,2,2,0,0,0,...,0,0,0,0,0,1,1,0,0,0
5,1,2,1,3,3,1,1,0,0,0,...,0,1,0,0,0,1,0,0,0,1
6,1,1,1,3,3,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,1
7,1,1,1,3,3,2,1,0,1,0,...,0,1,0,0,0,1,0,0,0,1
8,1,1,1,3,5,2,1,0,0,0,...,0,0,0,0,0,1,0,0,0,1
9,1,1,1,3,2,2,1,1,0,0,...,0,1,0,0,0,1,0,0,0,1
10,1,1,1,5,2,2,1,1,0,0,...,1,0,0,0,0,1,0,0,0,1
11,1,2,1,5,0,2,1,1,0,0,...,0,0,0,0,0,1,0,0,0,1
12,1,1,1,3,2,2,2,0,0,0,...,0,0,0,0,0,1,0,0,0,1
13,1,2,1,3,4,2,2,0,0,0,...,0,0,1,0,0,1,0,0,0,1
14,1,2,1,3,5,2,2,1,0,0,...,0,0,0,0,0,1,0,0,0,1
15,0,1,0,3,5,2,3,1,0,0,...,0,0,0,0,0,1,1,0,0,0
16,0,1,1,3,4,2,3,0,0,0,...,0,0,0,0,0,1,1,0,0,0
17,0,1,1,2,3,2,3,1,0,0,...,0,0,0,0,0,1,1,0,0,0
18,0,1,1,3,3,2,3,0,0,0,...,0,0,0,0,0,1,1,0,0,0
19,1,1,1,3,1,2,1,1,0,0,...,0,0,0,0,0,1,0,0,0,1

In [34]:
## Now need to split the data for train and test

X_rta = df_rta_dummies.drop(columns=["Accident_severity"])
y_rta = df_rta_dummies["Accident_severity"]

X_train, X_test, y_train, y_test = train_test_split(X_rta, y_rta, test_size=0.2)

print(X_train.shape)
print(X_test.shape)

(9852, 157)
(2464, 157)

In [32]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [30]:
y_pred = model.predict(X_test)

In [35]:
from sklearn.impute import SimpleImputer


imputer = SimpleImputer(missing_values="nan", strategy = 'mean')
imputer.fit(df_rta_dummies.iloc[:,:])

ValueError: 'X' and 'missing_values' types are expected to be both numerical. Got X.dtype=float64 and  type(missing_values)=<class 'str'>.

In [38]:
df_rta_dummies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12316 entries, 0 to 12315
Columns: 158 entries, Time to Light_conditions_Daylight
dtypes: int64(8), uint8(150)
memory usage: 2.5 MB